site_name: starlightDocs
theme: readthedocs
site_url: http://starlight-manual.readthedocs.io/
pages:
  - About: index.md
  - Features: features.md
  - Getting Started:
    - Installation: installation.md
    - User Interface: interface.md
    - Fog: fog.md
  - Support:
    - Known Issues: issues.md
    - Contact: contact.md

