site_name: Physical Starlight and Atmosphere
site_dir: psa
theme:
  name: material
  custom_dir: theme-extension
  favicon: img/physical-addons-favicon.svg
  font: false
    # text: Inter
  logo: img/physical-addons-favicon.svg
  palette:
    primary: black
  features:
    - navigation.top
  # features:
  #   - tabs
plugins:
  - search
site_url: https://www.physicaladdons.com/psa/
# google_analytics: ['UA-86947939-2', 'auto']
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.critic
  - attr_list
  - abbr
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      toc_depth: '1-2'
      permalink: true
nav:
  - Home: index.md
  - Getting Started: getting-started.md
    # - Updating: updating.md
  - Documentation: documentation.md
  - FAQ and contacts: faq.md
#     - Overview: overview.md
#     - Presets: presets.md
# #    - Atmosphere: atmosphere.md
#     - Ground: ground.md
# #    - Stars: stars.md
# #    - Artistic Values: artistic-values.md
#     - Clouds: clouds.md
  - Changelog: release-notes.md
    # - Release Notes: 
  # - About:
  #   - Physical Starlight and Atmosphere: about.md
  #   - Contacts: contacts.md
extra_css:
  - stylesheets/extra.css
  - stylesheets/home.css
extra_javascript:
  - javascripts/extra.js
extra:
  analytics:
    provider: plausible
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/PhysicalAddons
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/PhysicalAddons/
    - icon: fontawesome/brands/github
      link: https://github.com/PhysicalAddons/
