site_name: Physical Starlight and Atmosphere
theme:
  name: material
  features:
    - tabs
site_url: http://starlight-manual.readthedocs.io/
markdown_extensions:
  - admonition
pages:
  - About: index.md
  - Features: features.md
  - Getting Started:
    - Installation: installation.md
    - User Interface: interface.md
    - Fog: fog.md
  - Support:
    - Release Notes: release-notes.md
    - Frequently Asked Questions: faq.md
    - Known Issues: issues.md
    - Contact: contact.md

